apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  ports:
  - name: web-app-port
    port: 5005
    protocol: TCP
    targetPort: 3005
  selector:
    app: myapp
  type: ClusterIP$