apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: web-app
        image: bmuschko/nodejs-hello-world:1.0.0
        ports:
        - containerPort: 3000
          protocol: TCP$ 